apiVersion: 1

datasources:
  - name: Heimdall Postgres
    uid: postgres-observability
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      connMaxLifetime: 14400
      maxIdleConns: 5
      maxOpenConns: 20

  - name: Heimdall Loki
    uid: loki-observability
    type: loki
    access: proxy
    url: http://loki:3100
